apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uqex1k96y-nodejs 
  janus-idp.io/tekton: uqex1k96y-nodejs
  backstage.io/kubernetes-id: uqex1k96y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uqex1k96y-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml